version: 2.1

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk

    working_directory: ~/repo

    steps:
      - checkout
      - run: sh ./gradlew dependencies > .debricked-gradle-dependencies.txt
      # It is important that the generated dependency tree files are persisted and attached to the following scan step
      - persist_to_workspace:
          root: ~/repo
          paths:
            - '**.debricked-gradle-dependencies.txt'
            # Make sure to add all generated .debricked-gradle-dependencies.txt files
  scan:
    docker:
      - image: debricked/cli
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: debricked scan

workflows:
  debricked-scan:
    jobs:
      - build
      - scan:
          requires:
            - build
