
trigger:
  branches:
    include:
      - '*' # Run on all branches

resources:
  - repo: self

stages:
  - stage: debricked
    jobs:
      - job: debricked
        displayName: Debricked scan
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - script: mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
            displayName: 'mvn dependency:tree'
          - script: |
              env > env.list
              docker run -v $HOME:$HOME --env-file ./env.list debricked/scan
            displayName: Debricked scan
            env:
              DEBRICKED_TOKEN: $(DEBRICKED_TOKEN)